name: safe_psych
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - anthropic==0.93.0
      - google-genai==1.72.0
      - huggingface_hub==0.36.2
      - openai==2.31.0
      - python-dotenv==1.2.2
      - safetensors==0.7.0
      - sentencepiece==0.2.1
      - transformers==4.57.6
      - pandas==3.0.2
      - numpy==2.2.6
      - matplotlib==3.10.9
      - scipy==1.17.1
